На проверку Антону 28.04.2022. Останется написать workflow
Andreyhiitola/DOCKER_NGINX_proxy_NGINX_servers_ansible pull request #1
Opened 2022-04-28 16:17 UTC by Andreyhiitola

2022-04-30 07:36 UTC, Anton-Sagurov commented
Общие комментарий:
1. Удалить файл role_nginx_Fedora/tasks/.main.yml.swn
2. Создать файл `./.gitignore` и добавить строчку: `*.swn`

2022-04-30 08:04 UTC, Anton-Sagurov commented
Изменить [тут](https://github.com/Andreyhiitola/DOCKER_NGINX_proxy_NGINX_servers_ansible/blob/ab2610055dc502762010146c0a1463e41e945c78/role_nginx_Fedora/tasks/main.yml#L82):
```yaml
  - name: Copying the HTML code in the Directory
    copy:
      src: index.html.j2.yml                             
      dest: /var/www  
```

`files/index.html.j2.yml --> /var/www/index.html.j2.yml`
`Web Server Nginx работает с файлом: /var/www/index.html`


0. Вместо команды `copy -> template` 
1. Используем переменную вместо `/var/www` (допустим - nginx_files)
2. Не забудь изменить имя файла, после того как ты его переименуешь.
3. `dest: {{ nginx_files }}/index.html`

2022-04-30 08:13 UTC, Anton-Sagurov commented
Handlers:
Создать прерыватель: `Restart NGINX Container`, скопировав [таску](https://github.com/Andreyhiitola/DOCKER_NGINX_proxy_NGINX_servers_ansible/blob/ab2610055dc502762010146c0a1463e41e945c78/role_nginx_Fedora/tasks/main.yml#L87) и поместив ее в **handlers/main.yml**

2022-04-30 08:23 UTC, Anton-Sagurov requested changes

2022-04-30 08:23 UTC, Anton-Sagurov commented on playbook_nginx
> +    - role_nginx_proxy_Fedora
`nginx_proxy_Fedora`

2022-04-30 08:23 UTC, Anton-Sagurov commented on role_nginx_Fedora/files/index.html.j2.yml
> +Ansible OS Famaly: {{ ansible_distribution }}  {{ansible_distribution_major_version }}<br>
`{{ansible_distribution_major_version }}` -> `{{ ansible_distribution_major_version }}`

2022-04-30 08:23 UTC, Anton-Sagurov commented on role_nginx_Fedora/files/index.html.j2.yml
> +Ansible OS Famaly: {{ ansible_distribution }}  {{ansible_distribution_major_version }}<br>
```yaml
ansible_distribution:
  version: "9.0.1"
  name:  "CentOS"
  date:  "2022/01/24"
```
{{ ansible_distribution["version"] }} --> "9.0.1"

'{"version":"9.0.1", "name":  "CentOS", "date":  "2022/01/24"}'

ansible_versions = [""] тоже самое что и 
```yaml
ansible_vers:
  - element1
  - element2
  - element3
  - .....
  - elementN
```
Чтобы получить первый в списке элемент делай так: `{{ ansible_version[0] }}`

2022-04-30 08:23 UTC, Anton-Sagurov commented on role_nginx_Fedora/files/index.html.j2.yml
> +
Переименуй файл `index.html.j2.yml` -> `index.j2.html`

2022-04-30 08:23 UTC, Anton-Sagurov commented on role_nginx_Fedora/files/index.html.j2.yml
> +
Переместить файл в `templates/`

2022-04-30 08:23 UTC, Anton-Sagurov commented on role_nginx_Fedora/templates/index.html.j2.yml
> +
Этот файл должен быть заменен файлом из дироектории files.

2022-04-30 08:23 UTC, Anton-Sagurov commented on role_nginx_Fedora/defaults/main.yml
> +proxy: 192.168.1.129
Попробуй заменить на: `{{ balansir_proxy }}`

2022-04-30 08:23 UTC, Anton-Sagurov commented on role_nginx_Fedora/tasks/main.yml
> +      src: index.html.j2.yml
Не забудь тут изменить имя файла на `index.j2.html`

2022-04-30 08:23 UTC, Anton-Sagurov commented on role_nginx_Fedora/tasks/main.yml
> +      destination_port: "80"
Использовать переменную вместо порта 80

2022-04-30 08:23 UTC, Anton-Sagurov commented on role_nginx_Fedora/tasks/main.yml
> +      source: "{{ proxy }}"
Давай использовать переменную из hosts

2022-04-30 08:23 UTC, Anton-Sagurov commented on role_nginx_Fedora/tasks/main.yml
> +      source: 255.255.255.255
0.0.0.0/0

2022-04-30 08:23 UTC, Anton-Sagurov commented on role_nginx_proxy_Fedora/files/nginx.conf.j2.yml
> +    server2 192.168.1.108;
Обязательно используем ip адреса в виде переменных

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_Fedora/tasks/main.yml
> +      src: index.html.j2.yml
index.html.j2.yml   положил в папку files. Первоначально хотел положить в templatesб, но ansible не разрешил

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_Fedora/tasks/main.yml
> +        #    notify:
При изменении файлов в папке Index.html.j2.yml  увидел, что серера не обновляют  web страницу.  Поставил notify.  а далее handler на reboot nodes. Но что то пока не получилос

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_Fedora/tasks/main.yml
> +          # handlers:
Вот это handler

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_Fedora/tasks/main.yml
> +  - name: Iptables flush filter
Добавил правило для iptable для обноления при перезапуске

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_Fedora/tasks/main.yml
> +      source: 255.255.255.255
Вот эти правилом хочу отсечь весь трафик из интернета

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_Fedora/templates/index.html.j2.yml
> +<html>
Зтот файл удалю, сверху есть правильный

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_proxy_Fedora/files/nginx.conf.j2.yml
> +  upstream backend1 {
В этом конфигурационном файле найдо заменть на {{    }}.  Пока руки не дошли узнать будет ли это работать?

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_proxy_Fedora/files/nginx.conf.j2.yml
> +    server2 192.168.1.108;
Заменил на ALL_hosts: vars

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_proxy_Fedora/files/nginx.conf.j2.yml
> +  upstream backend1 {
Заменил на переменные

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_Fedora/tasks/main.yml
> +      source: "{{ proxy }}"
Изменил на переменную Hosts

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_Fedora/tasks/main.yml
> +      destination_port: "80"
Поменял на переменную в defaults

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_Fedora/tasks/main.yml
> +  - name: Iptables flush filter
Убрал это правило из iptables

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_Fedora/tasks/main.yml
> +          # handlers:
Добавил сюда handler, при изменении перезапускает  NGINX

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_Fedora/tasks/main.yml
> +        #    notify:
Исправил все работает

2022-05-03 15:04 UTC, Andreyhiitola commented on role_nginx_Fedora/tasks/main.yml
> +      src: index.html.j2.yml
Название файла переделал на  index.j2.html

2022-05-16 07:57 UTC, merged